# Generated by Django 3.1.5 on 2022-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20220218_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='field',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
